export const SESSION_IDLE_TIMEOUT_SETTING_KEY = 'SESSION_IDLE_TIMEOUT_MINUTES'
export const SESSION_IDLE_WARNING_SETTING_KEY = 'SESSION_IDLE_WARNING_MINUTES'

export const SESSION_IDLE_TIMEOUT_MIN_MINUTES = 5
export const SESSION_IDLE_TIMEOUT_MAX_MINUTES = 480
export const SESSION_IDLE_TIMEOUT_FALLBACK_MINUTES = 30

export const SESSION_IDLE_WARNING_MIN_MINUTES = 1
export const SESSION_IDLE_WARNING_MAX_MINUTES = 30
export const SESSION_IDLE_WARNING_FALLBACK_MINUTES = 5

export const SESSION_IDLE_TIMEOUT_CACHE_TTL_MS = 60_000

export const SESSION_ABSOLUTE_TIMEOUT_DEFAULT_HOURS = 8
