--*********************************************************************
--* 01_CONTAGEM.sql                                                    *
--* Contagens basicas por tabela apos a carga.                         *
--* Use como sanity check: se algum bloco retornar 0 onde deveria      *
--* ter dado, ha problema no script de carga correspondente.           *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

SELECT 'SG_PARAMETRO'          AS TABELA, COUNT(*) AS QTD FROM SIGEC.SG_PARAMETRO
UNION ALL SELECT 'SG_CLIENTE',            COUNT(*) FROM SIGEC.SG_CLIENTE
UNION ALL SELECT 'SG_HIST_CLIENTE',       COUNT(*) FROM SIGEC.SG_HIST_CLIENTE
UNION ALL SELECT 'SG_CONTRATO',           COUNT(*) FROM SIGEC.SG_CONTRATO
UNION ALL SELECT 'SG_HIST_CONTRATO',      COUNT(*) FROM SIGEC.SG_HIST_CONTRATO
UNION ALL SELECT 'SG_PARCELA',            COUNT(*) FROM SIGEC.SG_PARCELA
UNION ALL SELECT 'SG_PAGAMENTO',          COUNT(*) FROM SIGEC.SG_PAGAMENTO
UNION ALL SELECT 'SG_HIST_FINANCEIRO',    COUNT(*) FROM SIGEC.SG_HIST_FINANCEIRO
UNION ALL SELECT 'SG_RENEGOCIACAO',       COUNT(*) FROM SIGEC.SG_RENEGOCIACAO
UNION ALL SELECT 'SG_OPCAO_RENEGOCIACAO', COUNT(*) FROM SIGEC.SG_OPCAO_RENEGOCIACAO
UNION ALL SELECT 'SG_HIST_PROCESSAMENTO', COUNT(*) FROM SIGEC.SG_HIST_PROCESSAMENTO
UNION ALL SELECT 'SG_EVENTO_COBRANCA',    COUNT(*) FROM SIGEC.SG_EVENTO_COBRANCA
ORDER BY TABELA;

-- Distribuicao de contratos por status
SELECT ST_CONTRATO, COUNT(*) AS QT_CONTRATOS
  FROM SIGEC.SG_CONTRATO
 GROUP BY ST_CONTRATO
 ORDER BY ST_CONTRATO;

-- Distribuicao de parcelas por status
SELECT ST_PARCELA, COUNT(*) AS QT_PARCELAS
  FROM SIGEC.SG_PARCELA
 GROUP BY ST_PARCELA
 ORDER BY ST_PARCELA;

-- Distribuicao de pagamentos por canal
SELECT CD_CANAL, COUNT(*) AS QT_PAGAMENTOS, SUM(VR_PAGO) AS VR_TOTAL
  FROM SIGEC.SG_PAGAMENTO
 GROUP BY CD_CANAL
 ORDER BY CD_CANAL;
