--*********************************************************************
--* 08_PARAMETROS.sql                                                  *
--* Confere se todos os parametros obrigatorios do SIGEC foram         *
--* carregados e imprime seus valores atuais.                          *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

WITH REQUERIDOS AS (
  SELECT 'TAXA_JUROS_PADRAO'    AS CD FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'PCT_MULTA_PADRAO'     FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'LIMITE_JUROS_MAX'     FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'DIAS_INAD_LEVE'       FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'DIAS_INAD_MEDIO'      FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'DIAS_INAD_GRAVE'      FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'ENTRADA_MIN_RENEG'    FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'MAX_PARCELAS_RENEG'   FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'FATOR_ESPECIAL_LEGADO' FROM SYSIBM.SYSDUMMY1
  UNION ALL SELECT 'COMMIT_INTERVAL'      FROM SYSIBM.SYSDUMMY1
)
SELECT R.CD AS CD_PARAMETRO,
       P.VR_PARAMETRO,
       P.TP_PARAMETRO,
       CASE WHEN P.CD_PARAMETRO IS NULL THEN 'FALTANDO' ELSE 'OK' END AS SITUACAO
  FROM REQUERIDOS R
  LEFT JOIN SIGEC.SG_PARAMETRO P
    ON P.CD_PARAMETRO = R.CD
 ORDER BY R.CD;

-- Todos os parametros cadastrados
SELECT CD_PARAMETRO, VR_PARAMETRO, TP_PARAMETRO, DS_PARAMETRO
  FROM SIGEC.SG_PARAMETRO
 ORDER BY CD_PARAMETRO;
