export const ErrorRefs = {
  API_UNHANDLED: 'SGP-API-HANDLER-001',
  API_VALIDATION: 'SGP-API-VALIDATION-001',
  API_ROUTE_NOT_FOUND: 'SGP-API-ROUTE-404-001',
  RBAC_PERMISSION_DENIED: 'SGP-RBAC-CHECK-001',
  RBAC_UNAUTHENTICATED: 'SGP-RBAC-CHECK-002',
  CONVEYOR_CREATE_FAILED: 'SGP-CONVEYOR-CREATE-001',
  CONVEYOR_DETAIL_NOT_FOUND: 'SGP-CONVEYOR-DETAIL-001',
} as const

export type ErrorRef = (typeof ErrorRefs)[keyof typeof ErrorRefs]
