--*********************************************************************
--* Carga de SIGEC.SG_CLIENTE                                          *
--* 15 clientes ficticios (CPF/CNPJ fake) para o laboratorio.          *
--* CPF/CNPJ NAO devem coincidir com pessoas reais. Usam padroes       *
--* sequenciais / repetitivos (ex.: 111.444.777-35).                   *
--*                                                                    *
--* IDs de cliente sao IDENTITY: assume-se que a carga eh feita em     *
--* base recem-criada, portanto os IDs gerados serao 1..15 na ordem    *
--* dos INSERTs abaixo. Se a base ja tiver clientes, ajuste as         *
--* referencias em 03_CONTRATOS.sql via LOOKUP por NR_DOCUMENTO.       *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

-- ID 1
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO,
   USUARIO_INCLUSAO)
VALUES
  ('CPF', '11144477735', 'ANA MARIA DA SILVA (FAKE)', 'PF',
   'RUA DAS FLORES, 100', 'SAO PAULO', 'SP', '01000000',
   'N', 'A', 'SEED');

-- ID 2
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '22233344456', 'BRUNO COSTA PEREIRA (FAKE)', 'PF',
   'AV BRASIL, 2000', 'RIO DE JANEIRO', 'RJ', '20040002',
   'N', 'B', 'SEED');

-- ID 3
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '33344455567', 'CARLA ANDRADE LIMA (FAKE)', 'PF',
   'RUA XV DE NOVEMBRO, 500', 'CURITIBA', 'PR', '80020310',
   'S', 'C', 'SEED');

-- ID 4
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '44455566678', 'DANIEL MENDES OLIVEIRA (FAKE)', 'PF',
   'AV IPIRANGA, 800', 'PORTO ALEGRE', 'RS', '90160092',
   'N', 'B', 'SEED');

-- ID 5
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '55566677789', 'ELISA RODRIGUES CAMPOS (FAKE)', 'PF',
   'RUA DA PAZ, 45', 'BELO HORIZONTE', 'MG', '30110020',
   'S', 'D', 'SEED');

-- ID 6
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '66677788890', 'FERNANDO ALVES DIAS (FAKE)', 'PF',
   'RUA GENERAL CAMARA, 90', 'SALVADOR', 'BA', '40025010',
   'N', 'A', 'SEED');

-- ID 7
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '77788899901', 'GABRIELA FONSECA MELO (FAKE)', 'PF',
   'AV BEIRA MAR, 1500', 'FLORIANOPOLIS', 'SC', '88015700',
   'S', 'E', 'SEED');

-- ID 8
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '88899900012', 'HUGO SANTOS PINHEIRO (FAKE)', 'PF',
   'RUA DAS PALMEIRAS, 220', 'MANAUS', 'AM', '69010030',
   'N', 'C', 'SEED');

-- ID 9
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '99900011123', 'ISABELA TAVARES CRUZ (FAKE)', 'PF',
   'RUA DO SOL, 12', 'RECIFE', 'PE', '50030230',
   'N', 'B', 'SEED');

-- ID 10
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CPF', '10120130145', 'JOAO VITOR MARQUES (FAKE)', 'PF',
   'RUA CENTRAL, 77', 'GOIANIA', 'GO', '74015010',
   'N', 'A', 'SEED');

-- ID 11 - PJ
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CNP', '11222333000181', 'ALFA TECNOLOGIA LTDA (FAKE)', 'PJ',
   'AV PAULISTA, 1000, CJ 501', 'SAO PAULO', 'SP', '01310100',
   'N', 'A', 'SEED');

-- ID 12 - PJ
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CNP', '22333444000172', 'BETA INDUSTRIA E COMERCIO ME (FAKE)', 'PJ',
   'ROD BR 116, KM 25', 'CAMPINAS', 'SP', '13073003',
   'S', 'C', 'SEED');

-- ID 13 - PJ
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('CNP', '33444555000163', 'GAMA SERVICOS FINANCEIROS SA (FAKE)', 'PJ',
   'AV RIO BRANCO, 500, 10 ANDAR', 'RIO DE JANEIRO', 'RJ', '20040009',
   'N', 'B', 'SEED');

-- ID 14 - ESPECIAL (legado)
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('LE ', 'LEG0000000001', 'CLIENTE ESPECIAL LEGADO 001 (FAKE)', 'ES',
   'ENDERECO NAO INFORMADO NO LEGADO', 'BRASILIA', 'DF', '70000000',
   'S', 'E', 'SEED');

-- ID 15 - ESPECIAL (legado)
INSERT INTO SIGEC.SG_CLIENTE
  (TP_DOCUMENTO, NR_DOCUMENTO, NM_CLIENTE, TP_CLIENTE,
   ENDERECO, CIDADE, UF, CEP,
   IND_REINCIDENTE, CLASSIFICACAO_RISCO, USUARIO_INCLUSAO)
VALUES
  ('LE ', 'LEG0000000002', 'CLIENTE ESPECIAL LEGADO 002 (FAKE)', 'ES',
   'ENDERECO NAO INFORMADO NO LEGADO', 'BRASILIA', 'DF', '70000000',
   'N', 'D', 'SEED');

COMMIT;
