--*********************************************************************
--* SIGEC.SG_PAGAMENTO                                                 *
--* Pagamentos aplicados a uma parcela (integral, parcial ou excesso). *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

CREATE TABLE SIGEC.SG_PAGAMENTO (
  ID_PAGAMENTO      BIGINT        NOT NULL
    GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  ID_CONTRATO       VARCHAR(15)   NOT NULL,
  NR_PARCELA        SMALLINT      NOT NULL,
  VR_PAGO           DECIMAL(15,2) NOT NULL,
  DT_PAGAMENTO      DATE          NOT NULL,
  CD_CANAL          CHAR(3)       NOT NULL,
  NR_DOC_PAGTO      VARCHAR(30),
  ST_PAGAMENTO      CHAR(2)       NOT NULL WITH DEFAULT 'CF',
  VR_DIFERENCA      DECIMAL(15,2) NOT NULL WITH DEFAULT 0,
  DH_INCLUSAO       TIMESTAMP     NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_ALTERACAO      TIMESTAMP,
  USUARIO_INCLUSAO  VARCHAR(30)   NOT NULL,
  USUARIO_ALTERACAO VARCHAR(30),
  SITUACAO_REG      CHAR(1)       NOT NULL WITH DEFAULT 'A',
  CONSTRAINT PK_SG_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO),
  CONSTRAINT FK_SG_PGT_PAR FOREIGN KEY (ID_CONTRATO, NR_PARCELA)
    REFERENCES SIGEC.SG_PARCELA (ID_CONTRATO, NR_PARCELA) ON DELETE RESTRICT,
  CONSTRAINT CK_SG_PGT_CANAL  CHECK (CD_CANAL IN
    ('BOL','PIX','TED','DOC','CAX','CRT','LEG')),
  CONSTRAINT CK_SG_PGT_STATUS CHECK (ST_PAGAMENTO IN
    ('CF','PN','RJ','ES','CN')),
  CONSTRAINT CK_SG_PGT_VLR    CHECK (VR_PAGO > 0),
  CONSTRAINT CK_SG_PGT_SITREG CHECK (SITUACAO_REG IN ('A','I'))
);

CREATE INDEX SIGEC.IX_SG_PGT_CTR_PAR
  ON SIGEC.SG_PAGAMENTO (ID_CONTRATO, NR_PARCELA, DT_PAGAMENTO);

CREATE INDEX SIGEC.IX_SG_PGT_DATA
  ON SIGEC.SG_PAGAMENTO (DT_PAGAMENTO);

COMMENT ON TABLE SIGEC.SG_PAGAMENTO IS
  'Pagamentos aplicados a parcelas de contratos.';

COMMENT ON COLUMN SIGEC.SG_PAGAMENTO.ID_PAGAMENTO IS 'PK IDENTITY do pagamento.';
COMMENT ON COLUMN SIGEC.SG_PAGAMENTO.CD_CANAL     IS 'BOL boleto, PIX, TED, DOC, CAX caixa, CRT cartao, LEG legado.';
COMMENT ON COLUMN SIGEC.SG_PAGAMENTO.ST_PAGAMENTO IS 'CF confirmado, PN pendente, RJ rejeitado, ES estornado, CN cancelado.';
COMMENT ON COLUMN SIGEC.SG_PAGAMENTO.VR_DIFERENCA IS 'Diferenca (positiva=excesso / negativa=falta) em relacao ao saldo da parcela no ato do pagamento.';

COMMIT;
