--*********************************************************************
--* SIGEC.SG_HIST_FINANCEIRO                                           *
--* Eventos financeiros (baixa, estorno, juros, multa, rateio, etc.)   *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

CREATE TABLE SIGEC.SG_HIST_FINANCEIRO (
  ID_HIST_FIN       BIGINT        NOT NULL
    GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  ID_CONTRATO       VARCHAR(15)   NOT NULL,
  NR_PARCELA        SMALLINT,
  ID_PAGAMENTO      BIGINT,
  DT_EVENTO         TIMESTAMP     NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  TP_EVENTO         CHAR(3)       NOT NULL,
  VR_EVENTO         DECIMAL(15,2) NOT NULL WITH DEFAULT 0,
  VR_SALDO_ANT      DECIMAL(15,2),
  VR_SALDO_NOV      DECIMAL(15,2),
  DS_EVENTO         VARCHAR(240),
  DH_INCLUSAO       TIMESTAMP     NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_ALTERACAO      TIMESTAMP,
  USUARIO_INCLUSAO  VARCHAR(30)   NOT NULL,
  USUARIO_ALTERACAO VARCHAR(30),
  SITUACAO_REG      CHAR(1)       NOT NULL WITH DEFAULT 'A',
  CONSTRAINT PK_SG_HIST_FINANCEIRO PRIMARY KEY (ID_HIST_FIN),
  CONSTRAINT FK_HFI_CTR FOREIGN KEY (ID_CONTRATO)
    REFERENCES SIGEC.SG_CONTRATO (ID_CONTRATO) ON DELETE RESTRICT,
  CONSTRAINT FK_HFI_PGT FOREIGN KEY (ID_PAGAMENTO)
    REFERENCES SIGEC.SG_PAGAMENTO (ID_PAGAMENTO) ON DELETE SET NULL,
  CONSTRAINT CK_SG_HFI_TPEVT CHECK (TP_EVENTO IN
    ('BXP','BXT','EST','JUR','MUL','ATZ','REN','REC','AJU','CAN')),
  CONSTRAINT CK_SG_HFI_SITREG CHECK (SITUACAO_REG IN ('A','I'))
);

CREATE INDEX SIGEC.IX_SG_HFI_CTR
  ON SIGEC.SG_HIST_FINANCEIRO (ID_CONTRATO, DT_EVENTO DESC);

CREATE INDEX SIGEC.IX_SG_HFI_PAR
  ON SIGEC.SG_HIST_FINANCEIRO (ID_CONTRATO, NR_PARCELA, DT_EVENTO);

COMMENT ON TABLE SIGEC.SG_HIST_FINANCEIRO IS
  'Historico de eventos financeiros por contrato/parcela/pagamento.';

COMMENT ON COLUMN SIGEC.SG_HIST_FINANCEIRO.TP_EVENTO IS
  'BXP baixa parcial, BXT baixa total, EST estorno, JUR juros, MUL multa, ATZ atualizacao, REN renegociacao, REC recalculo, AJU ajuste manual, CAN cancelamento.';

COMMIT;
