--*********************************************************************
--* SIGEC.SG_RENEGOCIACAO                                              *
--* Propostas / renegociacoes vinculadas a um contrato.                *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

CREATE TABLE SIGEC.SG_RENEGOCIACAO (
  ID_RENEGOCIACAO   BIGINT        NOT NULL
    GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  ID_CONTRATO       VARCHAR(15)   NOT NULL,
  ST_RENEGOCIACAO   CHAR(2)       NOT NULL WITH DEFAULT 'PR',
  VR_ENTRADA        DECIMAL(15,2) NOT NULL WITH DEFAULT 0,
  QT_OPCOES         SMALLINT      NOT NULL WITH DEFAULT 0,
  DT_PROPOSTA       DATE          NOT NULL WITH DEFAULT CURRENT DATE,
  DT_APROVACAO      DATE,
  DT_ENCERRAMENTO   DATE,
  CLASS_RISCO       CHAR(1),
  VR_SALDO_ORIGEM   DECIMAL(15,2) NOT NULL WITH DEFAULT 0,
  DH_INCLUSAO       TIMESTAMP     NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_ALTERACAO      TIMESTAMP,
  USUARIO_INCLUSAO  VARCHAR(30)   NOT NULL,
  USUARIO_ALTERACAO VARCHAR(30),
  SITUACAO_REG      CHAR(1)       NOT NULL WITH DEFAULT 'A',
  CONSTRAINT PK_SG_RENEGOCIACAO PRIMARY KEY (ID_RENEGOCIACAO),
  CONSTRAINT FK_SG_REN_CTR FOREIGN KEY (ID_CONTRATO)
    REFERENCES SIGEC.SG_CONTRATO (ID_CONTRATO) ON DELETE RESTRICT,
  CONSTRAINT CK_SG_REN_STATUS CHECK (ST_RENEGOCIACAO IN
    ('PR','AP','RC','AT','EN')),
  CONSTRAINT CK_SG_REN_CLRISCO CHECK (CLASS_RISCO IN
    ('A','B','C','D','E') OR CLASS_RISCO IS NULL),
  CONSTRAINT CK_SG_REN_SITREG CHECK (SITUACAO_REG IN ('A','I'))
);

CREATE INDEX SIGEC.IX_SG_REN_CTR
  ON SIGEC.SG_RENEGOCIACAO (ID_CONTRATO, DT_PROPOSTA DESC);

CREATE INDEX SIGEC.IX_SG_REN_STATUS
  ON SIGEC.SG_RENEGOCIACAO (ST_RENEGOCIACAO);

COMMENT ON TABLE SIGEC.SG_RENEGOCIACAO IS
  'Propostas e renegociacoes de contratos inadimplentes.';

COMMENT ON COLUMN SIGEC.SG_RENEGOCIACAO.ST_RENEGOCIACAO IS
  'PR proposta, AP aprovada, RC recusada, AT ativa (com parcelas geradas), EN encerrada.';

COMMIT;
