--*********************************************************************
--* SIGEC.SG_OPCAO_RENEGOCIACAO                                        *
--* Opcoes (planos) ofertadas dentro de uma renegociacao.              *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

CREATE TABLE SIGEC.SG_OPCAO_RENEGOCIACAO (
  ID_RENEGOCIACAO   BIGINT        NOT NULL,
  NR_OPCAO          SMALLINT      NOT NULL,
  QT_PARCELAS       SMALLINT      NOT NULL,
  VR_PARCELA        DECIMAL(15,2) NOT NULL,
  VR_TOTAL          DECIMAL(15,2) NOT NULL,
  TX_APLICADA       DECIMAL(5,2)  NOT NULL WITH DEFAULT 0,
  IND_SELECIONADA   CHAR(1)       NOT NULL WITH DEFAULT 'N',
  DH_INCLUSAO       TIMESTAMP     NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_ALTERACAO      TIMESTAMP,
  USUARIO_INCLUSAO  VARCHAR(30)   NOT NULL,
  USUARIO_ALTERACAO VARCHAR(30),
  SITUACAO_REG      CHAR(1)       NOT NULL WITH DEFAULT 'A',
  CONSTRAINT PK_SG_OPCAO_RENEG PRIMARY KEY (ID_RENEGOCIACAO, NR_OPCAO),
  CONSTRAINT FK_SG_OPC_REN FOREIGN KEY (ID_RENEGOCIACAO)
    REFERENCES SIGEC.SG_RENEGOCIACAO (ID_RENEGOCIACAO) ON DELETE CASCADE,
  CONSTRAINT CK_SG_OPC_SEL  CHECK (IND_SELECIONADA IN ('S','N')),
  CONSTRAINT CK_SG_OPC_VLR  CHECK (VR_PARCELA >= 0 AND VR_TOTAL >= 0),
  CONSTRAINT CK_SG_OPC_SITREG CHECK (SITUACAO_REG IN ('A','I'))
);

COMMENT ON TABLE SIGEC.SG_OPCAO_RENEGOCIACAO IS
  'Opcoes de plano oferecidas dentro de uma renegociacao.';

COMMENT ON COLUMN SIGEC.SG_OPCAO_RENEGOCIACAO.IND_SELECIONADA IS
  'S se esta opcao foi a escolhida pelo cliente; N caso contrario.';

COMMIT;
