--*********************************************************************
--* SIGEC.SG_HIST_PROCESSAMENTO                                        *
--* Log de execucao de jobs batch (COBOL/JCL) do SIGEC.                *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

CREATE TABLE SIGEC.SG_HIST_PROCESSAMENTO (
  ID_PROCESSAMENTO  BIGINT       NOT NULL
    GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  NM_JOB            VARCHAR(30)  NOT NULL,
  NM_PROGRAMA       VARCHAR(30)  NOT NULL,
  DT_REFERENCIA     DATE         NOT NULL,
  DH_INICIO         TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_FIM            TIMESTAMP,
  ST_EXECUCAO       CHAR(2)      NOT NULL WITH DEFAULT 'EX',
  CD_RETORNO        INTEGER      NOT NULL WITH DEFAULT 0,
  QT_REG_LIDOS      INTEGER      NOT NULL WITH DEFAULT 0,
  QT_REG_GRAVADOS   INTEGER      NOT NULL WITH DEFAULT 0,
  QT_REG_REJEITADOS INTEGER      NOT NULL WITH DEFAULT 0,
  QT_COMMITS        INTEGER      NOT NULL WITH DEFAULT 0,
  DS_MENSAGEM       VARCHAR(240),
  DH_INCLUSAO       TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_ALTERACAO      TIMESTAMP,
  USUARIO_INCLUSAO  VARCHAR(30)  NOT NULL,
  USUARIO_ALTERACAO VARCHAR(30),
  SITUACAO_REG      CHAR(1)      NOT NULL WITH DEFAULT 'A',
  CONSTRAINT PK_SG_HIST_PROCESSAMENTO PRIMARY KEY (ID_PROCESSAMENTO),
  CONSTRAINT CK_SG_HPR_STEXEC CHECK (ST_EXECUCAO IN
    ('EX','OK','ER','AB','AV')),
  CONSTRAINT CK_SG_HPR_SITREG CHECK (SITUACAO_REG IN ('A','I'))
);

CREATE INDEX SIGEC.IX_SG_HPR_JOB
  ON SIGEC.SG_HIST_PROCESSAMENTO (NM_JOB, DT_REFERENCIA DESC);

CREATE INDEX SIGEC.IX_SG_HPR_PROG
  ON SIGEC.SG_HIST_PROCESSAMENTO (NM_PROGRAMA, DH_INICIO DESC);

COMMENT ON TABLE SIGEC.SG_HIST_PROCESSAMENTO IS
  'Log de execucao de jobs batch do SIGEC.';

COMMENT ON COLUMN SIGEC.SG_HIST_PROCESSAMENTO.ST_EXECUCAO IS
  'EX em execucao, OK concluido, ER erro, AB abendado, AV encerrado com avisos.';
COMMENT ON COLUMN SIGEC.SG_HIST_PROCESSAMENTO.CD_RETORNO IS
  'Return code do programa (0/4/8/12/16 no mainframe).';

COMMIT;
