--*********************************************************************
--* SIGEC.SG_EVENTO_COBRANCA                                           *
--* Eventos de cobranca (envio de boleto, ligacao, SMS, protesto...).  *
--*********************************************************************

SET CURRENT SCHEMA = SIGEC;

CREATE TABLE SIGEC.SG_EVENTO_COBRANCA (
  ID_EVENTO         BIGINT       NOT NULL
    GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  ID_CONTRATO       VARCHAR(15)  NOT NULL,
  NR_PARCELA        SMALLINT,
  DT_EVENTO         TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  TP_EVENTO         CHAR(3)      NOT NULL,
  CD_CANAL          CHAR(3),
  ST_EVENTO         CHAR(2)      NOT NULL WITH DEFAULT 'PE',
  DS_EVENTO         VARCHAR(240),
  DT_PROX_ACAO      DATE,
  DH_INCLUSAO       TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  DH_ALTERACAO      TIMESTAMP,
  USUARIO_INCLUSAO  VARCHAR(30)  NOT NULL,
  USUARIO_ALTERACAO VARCHAR(30),
  SITUACAO_REG      CHAR(1)      NOT NULL WITH DEFAULT 'A',
  CONSTRAINT PK_SG_EVENTO_COBRANCA PRIMARY KEY (ID_EVENTO),
  CONSTRAINT FK_SG_EVC_CTR FOREIGN KEY (ID_CONTRATO)
    REFERENCES SIGEC.SG_CONTRATO (ID_CONTRATO) ON DELETE CASCADE,
  CONSTRAINT CK_SG_EVC_TPEVT CHECK (TP_EVENTO IN
    ('AVI','BOL','SMS','EMA','LIG','CAR','NEG','PRO','SER','ACA')),
  CONSTRAINT CK_SG_EVC_STEVT CHECK (ST_EVENTO IN
    ('PE','EN','OK','FA','CA')),
  CONSTRAINT CK_SG_EVC_CANAL CHECK (CD_CANAL IN
    ('BOL','PIX','TED','DOC','CAX','CRT','LEG','SMS','EMA','TEL','CAR')
    OR CD_CANAL IS NULL),
  CONSTRAINT CK_SG_EVC_SITREG CHECK (SITUACAO_REG IN ('A','I'))
);

CREATE INDEX SIGEC.IX_SG_EVC_CTR
  ON SIGEC.SG_EVENTO_COBRANCA (ID_CONTRATO, DT_EVENTO DESC);

CREATE INDEX SIGEC.IX_SG_EVC_PROXACAO
  ON SIGEC.SG_EVENTO_COBRANCA (DT_PROX_ACAO, ST_EVENTO);

COMMENT ON TABLE SIGEC.SG_EVENTO_COBRANCA IS
  'Eventos e acoes de cobranca sobre contratos/parcelas.';

COMMENT ON COLUMN SIGEC.SG_EVENTO_COBRANCA.TP_EVENTO IS
  'AVI aviso, BOL boleto, SMS, EMA e-mail, LIG ligacao, CAR carta, NEG negociacao, PRO protesto, SER serasa, ACA acao judicial.';
COMMENT ON COLUMN SIGEC.SG_EVENTO_COBRANCA.ST_EVENTO IS
  'PE pendente, EN enviado, OK atendido, FA falha, CA cancelado.';

COMMIT;
